### ISSUE TITLE
Cloudinary implementation

### ISSUE THREAD

**Issue by granitn** [granitn/capstone-project#9]
## Value proposition

As a User
I want to be able to put my own photos on the entries
in order to have a visual reference to the machine i made the entry for

## Description

![image](https://github.com/granitn/capstone-project/assets/94522570/3272ac51-284f-430c-9b94-85cb23977479)

## Acceptance criteria

- the add and edit form show the upload form inside of them
- after uploading an image the secure url gets transferred into the "picture url" input
- the form can then be submitted to create a card displaying the uploaded image

## Tasks

- setting up cloudinary
- building upload form component 
- write "handleFileChange and submit handler"
- adding the upload form to form.js and edit.js
- make secure_url of response.json be the "Picture" input value

 

Size: m

**Comment by t0bbl** [comment]
LGTM
